help:
	@echo "Available targets:"
	@echo "  help                                     - Show this help message"
	@echo ""
	@echo "  mkdocs CMD=build|serve|gh-deploy         - [Build / Serve/ Deploy to GitHub Pages] web docs using mkdocs"
	@echo "  mkdocs-clean                             - Clean the web docs"
	@echo ""
	@echo "  mddocs-build                             - Build markdown docs using mddocs"
	@echo "  mddocs-clean                             - Clean the markdown docs"
	@echo "  mddocs-run                               - Run again mddocs to update docs"	
	@echo ""
	@echo "  bumpver LEVEL=major|minor|patch          - Bump version"
	
# --------------------------------------------------

.stamps:
	@if [ ! -d ".stamps" ]; then mkdir -p ".stamps"; fi

# --------------------------------------------------

MKDOCS_INSTALL = .stamps/mkdocs-install.done

$(MKDOCS_INSTALL): .stamps
	pip install mkdocs mkdocs-material mkdocstrings[python] mkdocs-gen-files 
	touch $(MKDOCS_INSTALL)

MKDOCS_DIR = docs-web

# $(MKDOCS_DIR):
# 	@if [ ! -d "$(MKDOCS_DIR)" ]; then mkdir -p "$(MKDOCS_DIR)"; fi

# mkdocs: $(MKDOCS_INSTALL) $(MKDOCS_DIR)
# 	PYTHONPATH=./src mkdocs $(CMD)

# --------------------------------------------------

PYUTILS_INSTALL = .stamps/pyutils-install.done

$(PYUTILS_INSTALL): .stamps
	git clone https://github.com/mirekfoo/pyutils.git
	pip install -e pyutils
	touch $(PYUTILS_INSTALL)

# --------------------------------------------------

mkdocs: $(MKDOCS_INSTALL) $(PYUTILS_INSTALL)
	PYTHONPATH=./src python -m mkdocs_pyapi $(CMD)

mkdocs-clean:
	rm -rf $(MKDOCS_DIR)
	rm -rf docs-web-site

# --------------------------------------------------

MDDOCS_INSTALL = .stamps/mddocs-install.done

$(MDDOCS_INSTALL): .stamps
	pip install git+https://github.com/mirekfoo/mddocs.git 
	touch $(MDDOCS_INSTALL)

mddocs-install: $(MDDOCS_INSTALL)

# --------------------------------------------------

MDDOCS_DIR = docs-md

PROJECT_SRC := $(wildcard src/mkdocs-pyapi/*.py)

MDDOCS_GENERATE = .stamps/mddocs_generate.done

$(MDDOCS_GENERATE): .stamps $(MDDOCS_INSTALL) $(PROJECT_SRC)
	PYTHONPATH=./src python -m mddocs 
	touch $(MDDOCS_GENERATE)

mddocs-build: \
	$(MDDOCS_GENERATE)

mddocs-clean:
	rm -rf $(MDDOCS_DIR)
	rm -f $(MDDOCS_GENERATE)

mddocs-run: \
	mddocs-clean \
	$(MDDOCS_GENERATE)

# --------------------------------------------------

BUMPVER_INSTALL = .stamps/bumpver-install.done

$(BUMPVER_INSTALL): .stamps
	pip install bumpver 
	touch $(BUMPVER_INSTALL)

bumpver: $(BUMPVER_INSTALL)
	bumpver update --$(LEVEL)
